const products = [{
    id: "1",
    img: "/assets/img/Barda_Pinot_Noir_2020-removebg-preview.png",
    name: "Barda Pinot Noir 2020",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "2",
    img: "/assets/img/trisquel-series-malbec-750cc.png",
    name: "Trisquel Series Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "3",
    img: "/assets/img/trivento-eolo-malbec-2011-botella-750-cc-removebg-preview.png",
    name: "Trivento Eolo Malbec 2011",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "4",
    img: "../assets/img/trivento-golden-reserve-malbec-2017-botella-750-cc.png",
    name: "Trivento Golden Reserve Malbec 2017",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "5",
    img: "../assets/img/trivento-reserve-malbec-2017-botella-750-cc-removebg-preview.png",
    name: "Trivento Reserve Malbec 2017",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "6",
    img: "../assets/img/vino-chocalan-reserva-carmenere-750-cc-removebg-preview.png",
    name: "Chocalan Reserva Carmenere",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "7",
    img: "../assets/img/vino-kaiken-mai-malbec-removebg-preview.png",
    name: "Kaiken Mai Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "8",
    img: "../assets/img/vino-kaiken-reserva-malbec-750cc-removebg-preview.png",
    name: "Kaiken Reserva Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "9",
    img: "../assets/img/vino-kaiken-terroir-series-corte-malbec-750cc-removebg-preview.png",
    name: "Kaiken Terroir Series Corte Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "10",
    img: "../assets/img/vino-kaiken-ultra-malbec-750cc-removebg-preview.png",
    name: "Kaiken Ultra Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "11",
    img: "../assets/img/vino-montes-alpha-malbec-750cc-removebg-preview.png",
    name: "Montes Alpha Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "12",
    img: "../assets/img/vino-montes-classic-series-malbec-reserva-750cc-removebg-preview.png",
    name: "Montes Classic Series Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "13",
    img: "../assets/img/vino-norton-malbec-reserva-botella-750-cc-removebg-preview.png",
    name: "Norton Malbec Reserva",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "14",
    img: "../assets/img/vino-odfjell-orzada-malbec-750cc-removebg-preview.png",
    name: "Odfjell Orzada Malbec",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "15",
    img: "../assets/img/Fincas_Notables_Cabernet_Franc_2018-removebg-preview.png",
    name: "Fincas Notables Cabernet Franc 2018",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "16",
    img: "../assets/img/Lagarde_Guarda_Malbec_D.O.C_2019-removebg-preview.png",
    name: "Lagarde Guarda Malbec D.O.C 2019",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "17",
    img: "../assets/img/Trapiche_Gran_Medalla_Malbec_2019-removebg-preview.png",
    name: "Trapiche Gran Medalla Malbec 2019",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "1",
    stock: 10,
},
{
    id: "18",
    img: "../assets/img/cs/bicicleta-cabernet-sauvignon-2018-botella-750-cc.png",
    name: "Bicicleta Cabernet Sauvignon 2018",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "19",
    img: "../assets/img/cs/cayetana-cabernet-sauvignon.png",
    name: "Cayetana Cavernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "20",
    img: "../assets/img/cs/cono-sur-reserva-especial-cabernet-sauvignon-2018-750-cc.png",
    name: "Cono Sur Reserva Cabernet Sauvignon 2018",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "21",
    img: "../assets/img/cs/diablo-volcanic-cabernet.png",
    name: "Diablo Volcanic Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "22",
    img: "../assets/img/cs/silencio-cabernet-sauvignon-2015-j9.png",
    name: "Silencio Cabernet Sauvignon 2015",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "23",
    img: "../assets/img/cs/unrated-cabernet-sauvignon.png",
    name: "Unrated Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "24",
    img: "../assets/img/cs/vino-alyan-gran-reserva-cabernet-sauvignon-botella-750cc.png",
    name: "Alyan Gran Reserva Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "25",
    img: "../assets/img/cs/vino-aquitania-cabernet-sauvignon-botella-750cc.png",
    name: "Aquitania Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "26",
    img: "../assets/img/cs/vino-casas-del-toqui-gran-toqui-cabernet-sauvignon.png",
    name: "Casas Del Toqui Gran Toqui Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "27",
    img: "../assets/img/cs/vino-casas-del-toqui-reserva-barrel-cabernet-sauvignon.png",
    name: "Casas Del Toqui Reserva Barrel Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "28",
    img: "../assets/img/cs/vino-chocalan-reserva-carmenere-750-cc.png",
    name: "Chocalan Reserva Carmenere",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "29",
    img: "../assets/img/cs/vino-kaiken-ultra-cabernet-sauvignon-750cc.png",
    name: "Kaiken Ultra Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "30",
    img: "../assets/img/cs/vino-los-vascos-cabernet-sauvignon-reserva.png",
    name: "Los Vascos Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "31",
    img: "../assets/img/cs/vino-odfjell-orzada-cabernet-sauvignon-750cc.png",
    name: "Ozarda Cabernet Sauvignon",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "2",
    stock: 10,
},
{
    id: "32",
    img: "../assets/img/merlot/aila-heaven-gran-reserva-merlot.png",
    name: "Alia Heaven Gran Reserva Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "33",
    img: "../assets/img/merlot/andetelmo-el-principal-750cc-removebg-preview.png",
    name: "Andetelmo El Principal Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "34",
    img: "../assets/img/merlot/bicicleta-merlot-2018-botella-750-cc-removebg-preview.png",
    name: "Bicicleta Merlot 2018",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "35",
    img: "../assets/img/merlot/casillero-del-diablo-rva-especial-merlot-2018-caja-12-botellas-750-cc-removebg-preview.png",
    name: "Casillero Del Diablo Merlot 2018",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "36",
    img: "../assets/img/merlot/cono-sur-reserva-especial-merlot-2018-botella-750-cc-removebg-preview.png",
    name: "Cono Sur Merlot 2018",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "37",
    img: "../assets/img/merlot/gran-reserva-merlot-750cc.png",
    name: "Gran Reserva Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "38",
    img: "../assets/img/merlot/marques-de-casa-concha-merlot-2016-botella-750-cc.png",
    name: "Maques De Casa Merlot 2016",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "39",
    img: "../assets/img/merlot/montes-alpha-merlot-removebg-preview.png",
    name: "Montes Alpha Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "40",
    img: "../assets/img/merlot/vino-alyan-gran-reserva-cabernet-sauvignon-botella-750cc-removebg-preview.png",
    name: "Alyan Gran Reserva Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "41",
    img: "../assets/img/merlot/vino-montes-classic-series-merlot-reserva-750cc-removebg-preview.png",
    name: "Montes Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},
{
    id: "42",
    img: "../assets/img/merlot/vino-montgras-day-one-merlot-750cc-removebg-preview.png",
    name: "Montgras Day One Merlot",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis aliquam aperiam, voluptate voluptas voluptates expedita nostrum mollitia.",
    idCat: "3",
    stock: 10,
},];

export const getProducts = ()=>{
    return new Promise ((resolve)=>{
        setTimeout(()=>{
            resolve(products)
        }, 200)
    })
};

export const getUnProducto = (id)=>{
    return new Promise (resolve =>{
        setTimeout(()=>{
            const productos = products.find(prod => prod.id === id)
            resolve(productos)
        }, 200)
    })
};

export const getProductoPorCategoria = (idCategoria)=>{
    return new Promise (resolve =>{
        setTimeout(()=>{
            const productoPorCategoria = products.filter(prod => prod.idCat === idCategoria)
            resolve (productoPorCategoria)
        }, 200)
    })
};